sudo: false

language: php

env:
  global:
    - SYMFONY_VERSION=""

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x@dev"

before_install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
